name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.13.0

      - name: Cache build artifacts
        uses: actions/cache@v3
        with:
          path: |
            zig-cache
            ~/.cache/zig
          key: ${{ runner.os }}-zig-${{ hashFiles('**/build.zig') }}
          restore-keys: |
            ${{ runner.os }}-zig-

      - name: Check formatting
        run: zig fmt --check .

      - name: Build
        run: zig build

      - name: Run tests
        run: zig build test